### ISSUE TITLE
4.232 having issues loading props frm OCM

### ISSUE THREAD

**Issue by ShujathMohd** [whatawurst/android_kernel_sony_msm8998#4]
Hey there,

Kernel 4.230 was working fine for loading props from OCM, However with upgrade of 4.232 it is not laoding props from the partition.

Same device tree 4.230 is working fine, and 4.232 isnt.

**Comment by shank03** [comment]
Did you try logging the init file as debugging

**Comment by shank03** [comment]
Could you explain it a little bit more ?

Like :
- How did you get to know it's not loading props ?
- How you know if props are loaded ?
- Any changes you made in file that could help in solving this issue..
- Log outputs

More information would help us solve it better 😊

**Comment by ShujathMohd** [comment]
> Could you explain it a little bit more ?
> 
> Like :
> 
> * How did you get to know it's not loading props ?
> * How you know if props are loaded ?
> * Any changes you made in file that could help in solving this issue..
> * Log outputs
> 
> More information would help us solve it better


it loads props from "/ocm/system-properties/cust.prop" 

Which have the below props which should be applied.


ro.build.description=G8141-user 9 47.2.A.10.107 172320177 release-keys

ro.product.brand=Sony
ro.product.vendor.brand=Sony
ro.product.name=G8141
ro.product.vendor.name=G8141
ro.product.device=G8141
ro.product.vendor.device=G8141
ro.build.version.incremental=172320177
ro.build.tags=release-keys
ro.build.fingerprint=Sony/G8141/G8141:9/47.2.A.10.107/172320177:user/release-keys
ro.vendor.build.fingerprint=Sony/G8141/G8141:9/47.2.A.10.107/172320177:user/release-keys
ro.bootimage.build.fingerprint=Sony/G8141/G8141:9/47.2.A.10.107/172320177:user/release-keys

And should return when do a getprop in adbshell, which is not happening.
Thats how I know it is not loading props.


No changes made, As I mentioned it worked fine with 4.230 , will get log output for more info

**Comment by shank03** [comment]
Maybe any spelling mistake in path in the init file ?

**Comment by ShujathMohd** [comment]
> Maybe any spelling mistake in path in the init file ?

Spellings are fine, maybe log will help, will get it asap

Again it works fine with 4.230(No changes in device tree).

Im closing this issue for now, will get back with more testing and logs  :)

**Comment by derfelot** [comment]
strange, nothing has changed in the init and /ocm should also still be mounted:

https://github.com/whatawurst/android_kernel_sony_msm8998/commit/115f219bebc84485b376497adcc9657357e14095#diff-92b850d252477aff69cd191ad10cb77f

I'll see tonight if if i can reproduce the issue. But you can check your dmesg (after boot) for messages containing 'ocm'. It should be verbose enough to print to kernel log.

**Comment by ShujathMohd** [comment]
Aplogies,
My ROM sources were messed, 
Resynced and confirmed its working fine.

**Comment by derfelot** [comment]
Great, would have surprised me if any issues came from the kernel.
