### ISSUE TITLE
Update Wifi drivers

### ISSUE THREAD

**Issue by Flamefire** [whatawurst/android_kernel_sony_msm8998#74]
Would it make sense to update the Wifi drivers using the codelinearo repos? I.e. there is tag LA.UM.7.2.r2-13100-8x98.0 available:

- https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0/-/tree/LA.UM.7.2.r2-13100-8x98.0
- https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/fw-api/-/tree/LA.UM.7.2.r2-13100-8x98.0
- https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn/tree/LA.UM.7.2.r2-13100-8x98.0

Latest merge seems to be [LA.UM.7.2.r2-09300-8x98.0](https://github.com/whatawurst/android_kernel_sony_msm8998/pull/45)

Cross link to discussion on tag naming: https://github.com/whatawurst/android_kernel_sony_msm8998/pull/33#issuecomment-885748622

**Comment by derfelot** [comment]
Yes, as long as it doesn't cause any issues.

The last tag I merged was LA.UM.7.2.r2-11600-8x98.0 ( https://github.com/whatawurst/android_kernel_sony_msm8998/commit/a0865f40baf69fe12eab72ed4d536de0116f02a7 )

Both fw-api and qca-wifi-host-cmn haven't had any updates in a while (despite newer tags).

**Comment by Flamefire** [comment]
> Both fw-api and qca-wifi-host-cmn haven't had any updates in a while (despite newer tags).

Ups, true. And the only new commit in qcacld-3.0 is https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0/-/commit/2a466d1f25320aa5a68e5b37f4a87d4e59b7d02a which was mentioned in previous ASB and I have that already with https://github.com/Flamefire/android_kernel_sony_msm8998/commit/3cdae0a0fd2e3cf3fbd0726d23bafc6682ae9e17 which you may cherry-pick if you like.

Reason why I checked this is a commit linked in the Nov ASB: https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0/-/commit/c1dba00faf5661f3053f4d021ebd6794136f4eb5

However that fixes a bug introduced [earlier](https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0/-/commit/a7f1c222a90ad29bf1405c0b2be07ab435d30541) which we don't have. Checking the tags I found it only in the tags   LA.UM.10.9.1.r1, LA.UM.10.9.1.r1.1, LA.UM.9.2.c25, LA.UM.9.2.c26

So I guess not relevant to us unless we want to track 9.2 but not sure what the `c` means (instead of `r`)

**Comment by derfelot** [comment]
Not sure if i've mentioned it before in a comment here, but we can't really track newer tags than 7.4, since our fw is not really compatible with it. The maximum wifi speed drops dramatically. Thanks for the patches.
