### ISSUE TITLE
Android auto does not work on ROMs using this kernel

### ISSUE THREAD

**Issue by WilcoSnel** [whatawurst/android_kernel_sony_msm8998#76]
Both havoc os and lineage os don't have working android auto for several versions now. It seems they use the same kernel which would explain why it has not been working for some versions and stopped working around the same time for both roms.

If I can help with logs or anything, please let me know.

**Comment by derfelot** [comment]
I am working on some updates now. I don't have any way to test AndroidAuto, but once i release a new version (and if it still doesn't work), I will probably ask for some logs.

**Comment by WilcoSnel** [comment]
That's perfect! Thanks a lot. If you need logs, no problem. Glad to help

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by derfelot** [comment]
Hello,

have you had the chance to update to the latest build + latest official Gapps?

**Comment by WilcoSnel** [comment]
Hi,
Unfortunately not. But I'll have a go this weekend. Will let you know after.
Kind regards,
Wilco

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WilcoSnel** [comment]
I had some time today so updated to the latest build and mtg. Dirty flash though. But works fine so far. Android auto is still not working unfortunately.

What would be the best way to gather logs for you? Does the bug rapport function gather kernel details too? Or should I use something else? My phone is rooted btw. So maybe that makes it easier to gather kernel logs another way?


Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by derfelot** [comment]
Hello,

the best would be to just grab a full logcat, soon after you are trying to use the app/connect to car. Full meaning `logcat -b all` . You can either do that via adb, or directly run it on the phone (as root) and redirect the output somewhere onto sdcard or so.

Btw, you can just send it to my github associated e-mail address.

**Comment by WilcoSnel** [comment]
Ok, thanks for clearing that up.
Ended up using logcat extreme. Set it to verbose logging and recorded attached logfile.

Hopefully you can find something.
If you need more logging or I have to change some logging settings, let me know. I'm glad to help out :)

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by derfelot** [comment]
thanks, i'll try to have a look this weekend. can't promise anything, as I don't know of a way to emulate a car connection to test changes.

**Comment by derfelot** [comment]
ok, i think i found a way. btw, i highly doubt that this is a kernel issue. The reason why you are seeing this on other roms too, is that most other things (device config etc) are also the same there, as they are based on our repos.

**Comment by WilcoSnel** [comment]
Ah OK. So any idea what repo could be the problem? I guess there are multiple related to the xz1 compact? If I should report the problem on another github page, let me know.

Btw, I noticed below post. But I'm not sure if this is a workaround or an actual root cause fix.

https://forum.xda-developers.com/t/microg-android-auto-fully-working.4319159/post-87948495

Anyway, maybe it'll help with further diagnosing the issue. Thanks again for looking into this.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by derfelot** [comment]
I think it has to do with our usb init script, apparently it needs something special for the accessories to work. I seem to have made it work on the emulator. Please try adding the following lines at the end of `/vendor/etc/init/hw/init.yoshino.usb.rc` and then reboot :

```
################################################################################
# The following are USB audio/accessary mode related composition.
# We need to use Google decided VID and PID to pass CTS tests
#
on property:sys.usb.config=accessory && property:sys.usb.configfs=1
    write /config/usb_gadget/g1/configs/b.1/strings/0x409/configuration "accessory"
    rm /config/usb_gadget/g1/configs/b.1/f1
    rm /config/usb_gadget/g1/configs/b.1/f2
    rm /config/usb_gadget/g1/configs/b.1/f3
    rm /config/usb_gadget/g1/configs/b.1/f4
    rm /config/usb_gadget/g1/configs/b.1/f5
    rm /config/usb_gadget/g1/configs/b.1/f6
    write /config/usb_gadget/g1/idVendor 0x18d1
    write /config/usb_gadget/g1/idProduct 0x2d00
    symlink /config/usb_gadget/g1/functions/accessory.gs2 /config/usb_gadget/g1/configs/b.1/f1
    write /config/usb_gadget/g1/UDC ${sys.usb.controller}
    setprop sys.usb.state ${sys.usb.config}

on property:sys.usb.config=accessory,adb && property:sys.usb.configfs=1
    start adbd

on property:sys.usb.ffs.ready=1 && property:sys.usb.config=accessory,adb && property:sys.usb.configfs=1
    write /config/usb_gadget/g1/configs/b.1/strings/0x409/configuration "accessory_adb"
    rm /config/usb_gadget/g1/configs/b.1/f1
    rm /config/usb_gadget/g1/configs/b.1/f2
    rm /config/usb_gadget/g1/configs/b.1/f3
    rm /config/usb_gadget/g1/configs/b.1/f4
    rm /config/usb_gadget/g1/configs/b.1/f5
    rm /config/usb_gadget/g1/configs/b.1/f6
    write /config/usb_gadget/g1/idVendor 0x18d1
    write /config/usb_gadget/g1/idProduct 0x2d01
    symlink /config/usb_gadget/g1/functions/accessory.gs2 /config/usb_gadget/g1/configs/b.1/f1
    symlink /config/usb_gadget/g1/functions/ffs.adb /config/usb_gadget/g1/configs/b.1/f2
    write /config/usb_gadget/g1/UDC ${sys.usb.controller}
    setprop sys.usb.state ${sys.usb.config}

on property:sys.usb.config=audio_source && property:sys.usb.configfs=1
    write /config/usb_gadget/g1/configs/b.1/strings/0x409/configuration "audiosource"
    rm /config/usb_gadget/g1/configs/b.1/f1
    rm /config/usb_gadget/g1/configs/b.1/f2
    rm /config/usb_gadget/g1/configs/b.1/f3
    rm /config/usb_gadget/g1/configs/b.1/f4
    rm /config/usb_gadget/g1/configs/b.1/f5
    rm /config/usb_gadget/g1/configs/b.1/f6
    write /config/usb_gadget/g1/idVendor 0x18d1
    write /config/usb_gadget/g1/idProduct 0x2d02
    symlink /config/usb_gadget/g1/functions/audio_source.gs3 /config/usb_gadget/g1/configs/b.1/f1
    write /config/usb_gadget/g1/UDC ${sys.usb.controller}
    setprop sys.usb.state ${sys.usb.config}

on property:sys.usb.config=audio_source,adb && property:sys.usb.configfs=1
    start adbd

on property:sys.usb.ffs.ready=1 && property:sys.usb.config=audio_source,adb && property:sys.usb.configfs=1
    write /config/usb_gadget/g1/configs/b.1/strings/0x409/configuration "audiosource_adb"
    rm /config/usb_gadget/g1/configs/b.1/f1
    rm /config/usb_gadget/g1/configs/b.1/f2
    rm /config/usb_gadget/g1/configs/b.1/f3
    rm /config/usb_gadget/g1/configs/b.1/f4
    rm /config/usb_gadget/g1/configs/b.1/f5
    rm /config/usb_gadget/g1/configs/b.1/f6
    write /config/usb_gadget/g1/idVendor 0x18d1
    write /config/usb_gadget/g1/idProduct 0x2d03
    symlink /config/usb_gadget/g1/functions/audio_source.gs3 /config/usb_gadget/g1/configs/b.1/f1
    symlink /config/usb_gadget/g1/functions/ffs.adb /config/usb_gadget/g1/configs/b.1/f2
    write /config/usb_gadget/g1/UDC ${sys.usb.controller}
    setprop sys.usb.state ${sys.usb.config}

on property:sys.usb.config=accessory,audio_source && property:sys.usb.configfs=1
    write /config/usb_gadget/g1/configs/b.1/strings/0x409/configuration "accessory_audiosource"
    rm /config/usb_gadget/g1/configs/b.1/f1
    rm /config/usb_gadget/g1/configs/b.1/f2
    rm /config/usb_gadget/g1/configs/b.1/f3
    rm /config/usb_gadget/g1/configs/b.1/f4
    rm /config/usb_gadget/g1/configs/b.1/f5
    rm /config/usb_gadget/g1/configs/b.1/f6
    write /config/usb_gadget/g1/idVendor 0x18d1
    write /config/usb_gadget/g1/idProduct 0x2d04
    symlink /config/usb_gadget/g1/functions/accessory.gs2 /config/usb_gadget/g1/configs/b.1/f1
    symlink /config/usb_gadget/g1/functions/audio_source.gs3 /config/usb_gadget/g1/configs/b.1/f2
    write /config/usb_gadget/g1/UDC ${sys.usb.controller}
    setprop sys.usb.state ${sys.usb.config}

on property:sys.usb.config=accessory,audio_source,adb && property:sys.usb.configfs=1
    start adbd

on property:sys.usb.ffs.ready=1 && property:sys.usb.config=accessory,audio_source,adb && property:sys.usb.configfs=1
    write /config/usb_gadget/g1/configs/b.1/strings/0x409/configuration "accessory_audiosource_adb"
    rm /config/usb_gadget/g1/configs/b.1/f1
    rm /config/usb_gadget/g1/configs/b.1/f2
    rm /config/usb_gadget/g1/configs/b.1/f3
    rm /config/usb_gadget/g1/configs/b.1/f4
    rm /config/usb_gadget/g1/configs/b.1/f5
    rm /config/usb_gadget/g1/configs/b.1/f6
    write /config/usb_gadget/g1/idVendor 0x18d1
    write /config/usb_gadget/g1/idProduct 0x2d05
    symlink /config/usb_gadget/g1/functions/accessory.gs2 /config/usb_gadget/g1/configs/b.1/f1
    symlink /config/usb_gadget/g1/functions/audio_source.gs3 /config/usb_gadget/g1/configs/b.1/f2
    symlink /config/usb_gadget/g1/functions/ffs.adb /config/usb_gadget/g1/configs/b.1/f3
    write /config/usb_gadget/g1/UDC ${sys.usb.controller}
    setprop sys.usb.state ${sys.usb.config}
```

I will still go through it to see if everything makes sense and if everything else USB related still works. Please also have a try to test other USB usecases after adding this.

Thanks

**Comment by WilcoSnel** [comment]
It works! First try. Genius mate!

As far as testing goes. Tried simply charging, connecting external storage (opened, renamed, deleted stuff), adb connection with PC and android auto of course. All works without any problems. Anything else you'd like me to test? Does this additional piece of code still need further refinement? Or will it stay as is? In case of the latter I'd like to post this to the xda forum. With your permission of course. I know of a couple others who'd love to get AA working with this ROM. Let me know.

Anyway, for me personally this perfects the ROM. Thanks a million. Anywhere I can donate? Don't hesitate to ask if you need anymore testing btw. Thanks again.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by derfelot** [comment]
That's great, thanks for testing. I don't think the code will change considerably, and I will include the change in the next release. In the meantime, feel free to link this on XDA for other people to apply that want to get it working.

If you would like to donate, it is always appreciated and you can find a link on my AFH profile: https://androidfilehost.com/?w=profile&uid=24052804347840143

I will close this as resolved :)

**Comment by derfelot** [comment]
Oh, one more thing. Does audio playback over USB work as well? Note sure I can test this.

**Comment by WilcoSnel** [comment]
Good one. Just tested it. Works with the adapter that goes with the XZ2 compact. It doesn't work with the adapter of the Samsung Galaxy S20. But I believe that's an actual hardware incompatibility thing. The S20 adapter doesn't work with a stock XZ2 compact either. Another thing to cross of the list :D

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by WilcoSnel** [comment]
Scratch that! It's the other way around. Works with the S20 adapter. Doesn't work with the XZ2 compact adapter

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by derfelot** [comment]
OK, thanks for testing. I would also assume that it's just some kind of incompatibility then. As long as one works I assume it should be OK.
