### ISSUE TITLE
Kernel erroneously hides magisk su file

### ISSUE THREAD

**Issue by second2050** [whatawurst/android_kernel_sony_msm8998#92]
This kernel seems to hide the su binary after some time which makes Magisk 26.1 show `installed: N/A` which makes it unusable. Switching to the root user then only works when calling the `magisk` binary with the parameter `su` until the device is rebooted.

This seems to be caused by the commit 9a2b419da802255fe5d23cd794c0c97200566c4c, according to [this](https://github.com/topjohnwu/Magisk/issues/6914#issuecomment-1538541530), which was reverted in at least one instance by the LineageOS team in one of their repos here LineageOS/android_kernel_motorola_msm8998@ebe85fff23128cc570d4c5c60decf30fbe129bc1

**Comment by derfelot** [comment]
Thanks, I am aware of it. It's already on the list.

**Comment by derfelot** [comment]
This PR should fix it: https://github.com/whatawurst/android_kernel_sony_msm8998/pull/93

Going to make a kernel test build before merging it
